<?php

namespace Cleantech\DirectorioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DropUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DropUserRepository extends EntityRepository
{
}
